version: '3.8'

services:
  app:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    ports:
      - 6006:6006
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
    depends_on:
      - db_coding_test
  db_coding_test:
    container_name: coding_test_db
    platform: linux/x86_64
    image: mysql:5.7
    ports: 
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment: 
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  coding_test_db: